version: '3.8'

services:
  # FastAPI应用
  app:
    build: .
    container_name: exam_site_backend_app
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
    depends_on:
      - db
    networks:
      - exam_network
    volumes:
      - ./logs:/app/logs
    expose:
      - "8000"

  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: exam_site_backend_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - exam_network
    expose:
      - "3306"

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: exam_site_backend_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - exam_network

volumes:
  mysql_data:

networks:
  exam_network:
    driver: bridge 