"""sync to team data dictionary

Revision ID: 82edd0816690
Revises: 8c8a3ed14edb
Create Date: 2025-08-02 19:00:17.402492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82edd0816690'
down_revision: Union[str, Sequence[str], None] = '8c8a3ed14edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='联系电话',
               existing_comment='手机号',
               existing_nullable=False)
    op.alter_column('candidates', 'address',
               existing_type=mysql.TEXT(),
               comment='地址',
               existing_comment='联系地址',
               existing_nullable=True)
    op.alter_column('candidates', 'notes',
               existing_type=mysql.TEXT(),
               comment='备注',
               existing_comment='备注信息',
               existing_nullable=True)
    op.create_foreign_key(None, 'candidates', 'exam_products', ['exam_product_id'], ['id'])
    op.alter_column('exam_products', 'code',
               existing_type=mysql.VARCHAR(length=50),
               comment='产品代码',
               existing_nullable=True,
               existing_server_default=sa.text("'PROD_001'"))
    op.alter_column('exam_products', 'category',
               existing_type=mysql.ENUM('VLOS', 'BVLOS'),
               comment='考试类别',
               existing_nullable=True,
               existing_server_default=sa.text("'VLOS'"))
    op.alter_column('exam_products', 'exam_type',
               existing_type=mysql.ENUM('MULTIROTOR', 'FIXED_WING', 'VTOL'),
               comment='考试类型',
               existing_nullable=True,
               existing_server_default=sa.text("'MULTIROTOR'"))
    op.alter_column('exam_products', 'exam_class',
               existing_type=mysql.ENUM('AGRICULTURE', 'POWER_INSPECTION', 'FILM_PHOTOGRAPHY', 'LOGISTICS'),
               comment='考试等级',
               existing_nullable=True,
               existing_server_default=sa.text("'AGRICULTURE'"))
    op.alter_column('exam_products', 'exam_level',
               existing_type=mysql.ENUM('PILOT', 'CAPTAIN', 'INSTRUCTOR'),
               comment='考试级别',
               existing_nullable=True,
               existing_server_default=sa.text("'PILOT'"))
    op.alter_column('exam_products', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               comment='考试时长(分钟)',
               existing_nullable=True,
               existing_server_default=sa.text("'120'"))
    op.alter_column('exam_products', 'theory_pass_score',
               existing_type=mysql.INTEGER(),
               comment='理论考试及格分数',
               existing_nullable=True,
               existing_server_default=sa.text("'80'"))
    op.alter_column('exam_products', 'practical_pass_score',
               existing_type=mysql.INTEGER(),
               comment='实操考试及格分数',
               existing_nullable=True,
               existing_server_default=sa.text("'80'"))
    op.alter_column('exam_products', 'training_hours',
               existing_type=mysql.INTEGER(),
               comment='培训时长(小时)',
               existing_nullable=True,
               existing_server_default=sa.text("'40'"))
    op.alter_column('exam_products', 'price',
               existing_type=mysql.FLOAT(),
               comment='考试费用',
               existing_nullable=True,
               existing_server_default=sa.text("'1000'"))
    op.alter_column('exam_products', 'training_price',
               existing_type=mysql.FLOAT(),
               comment='培训费用',
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('exam_products', 'requirements',
               existing_type=mysql.TEXT(),
               comment='考试要求',
               existing_comment='报考要求',
               existing_nullable=True)
    op.alter_column('exam_products', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               comment='是否激活',
               existing_comment='是否启用',
               existing_nullable=True)
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'is_active')
    op.alter_column('schedules', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='状态',
               existing_comment='排期状态',
               existing_nullable=True)
    op.alter_column('schedules', 'check_in_time',
               existing_type=mysql.DATETIME(),
               comment='扫码签到时间',
               existing_comment='签到时间',
               existing_nullable=True)
    op.alter_column('schedules', 'estimated_wait_time',
               existing_type=mysql.INTEGER(),
               comment='预计等待时间',
               existing_comment='预估等待时间（分钟）',
               existing_nullable=True)
    op.alter_column('schedules', 'notes',
               existing_type=mysql.TEXT(),
               comment='备注',
               existing_comment='备注信息',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('venues', 'capacity')
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否启用'))
    op.add_column('venues', sa.Column('description', mysql.TEXT(), nullable=True, comment='考场描述'))
    op.add_column('venues', sa.Column('capacity', mysql.INTEGER(), server_default=sa.text("'50'"), autoincrement=False, nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('schedules', 'notes',
               existing_type=mysql.TEXT(),
               comment='备注信息',
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('schedules', 'estimated_wait_time',
               existing_type=mysql.INTEGER(),
               comment='预估等待时间（分钟）',
               existing_comment='预计等待时间',
               existing_nullable=True)
    op.alter_column('schedules', 'check_in_time',
               existing_type=mysql.DATETIME(),
               comment='签到时间',
               existing_comment='扫码签到时间',
               existing_nullable=True)
    op.alter_column('schedules', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='排期状态',
               existing_comment='状态',
               existing_nullable=True)
    op.add_column('roles', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否激活'))
    op.add_column('roles', sa.Column('description', mysql.TEXT(), nullable=True, comment='角色描述'))
    op.add_column('roles', sa.Column('permissions', mysql.TEXT(), nullable=True, comment='权限列表，JSON格式'))
    op.alter_column('exam_products', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_comment='是否激活',
               existing_nullable=True)
    op.alter_column('exam_products', 'requirements',
               existing_type=mysql.TEXT(),
               comment='报考要求',
               existing_comment='考试要求',
               existing_nullable=True)
    op.alter_column('exam_products', 'training_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='培训费用',
               existing_nullable=True,
               existing_server_default=sa.text("'2000'"))
    op.alter_column('exam_products', 'price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='考试费用',
               existing_nullable=True,
               existing_server_default=sa.text("'1000'"))
    op.alter_column('exam_products', 'training_hours',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='培训时长(小时)',
               existing_nullable=True,
               existing_server_default=sa.text("'40'"))
    op.alter_column('exam_products', 'practical_pass_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='实操考试及格分数',
               existing_nullable=True,
               existing_server_default=sa.text("'80'"))
    op.alter_column('exam_products', 'theory_pass_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='理论考试及格分数',
               existing_nullable=True,
               existing_server_default=sa.text("'80'"))
    op.alter_column('exam_products', 'duration_minutes',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='考试时长(分钟)',
               existing_nullable=True,
               existing_server_default=sa.text("'120'"))
    op.alter_column('exam_products', 'exam_level',
               existing_type=mysql.ENUM('PILOT', 'CAPTAIN', 'INSTRUCTOR'),
               comment=None,
               existing_comment='考试级别',
               existing_nullable=True,
               existing_server_default=sa.text("'PILOT'"))
    op.alter_column('exam_products', 'exam_class',
               existing_type=mysql.ENUM('AGRICULTURE', 'POWER_INSPECTION', 'FILM_PHOTOGRAPHY', 'LOGISTICS'),
               comment=None,
               existing_comment='考试等级',
               existing_nullable=True,
               existing_server_default=sa.text("'AGRICULTURE'"))
    op.alter_column('exam_products', 'exam_type',
               existing_type=mysql.ENUM('MULTIROTOR', 'FIXED_WING', 'VTOL'),
               comment=None,
               existing_comment='考试类型',
               existing_nullable=True,
               existing_server_default=sa.text("'MULTIROTOR'"))
    op.alter_column('exam_products', 'category',
               existing_type=mysql.ENUM('VLOS', 'BVLOS'),
               comment=None,
               existing_comment='考试类别',
               existing_nullable=True,
               existing_server_default=sa.text("'VLOS'"))
    op.alter_column('exam_products', 'code',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='产品代码',
               existing_nullable=True,
               existing_server_default=sa.text("'PROD_001'"))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.alter_column('candidates', 'notes',
               existing_type=mysql.TEXT(),
               comment='备注信息',
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('candidates', 'address',
               existing_type=mysql.TEXT(),
               comment='联系地址',
               existing_comment='地址',
               existing_nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号',
               existing_comment='联系电话',
               existing_nullable=False)
    # ### end Alembic commands ###
