"""change_schedule_enums_to_strings

Revision ID: aa291679f89c
Revises: f2fad9704da5
Create Date: 2025-08-01 15:02:24.544636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa291679f89c'
down_revision: Union[str, Sequence[str], None] = 'f2fad9704da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'schedule_type',
               existing_type=mysql.ENUM('THEORY', 'PRACTICAL'),
               type_=sa.String(length=20),
               existing_comment='排期类型',
               existing_nullable=False)
    op.alter_column('schedules', 'status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               type_=sa.String(length=20),
               existing_comment='排期状态',
               existing_nullable=True)
    op.alter_column('schedules', 'check_in_status',
               existing_type=mysql.ENUM('NOT_CHECKED_IN', 'CHECKED_IN', 'LATE'),
               type_=sa.String(length=20),
               existing_comment='签到状态',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'check_in_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('NOT_CHECKED_IN', 'CHECKED_IN', 'LATE'),
               existing_comment='签到状态',
               existing_nullable=True)
    op.alter_column('schedules', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'),
               existing_comment='排期状态',
               existing_nullable=True)
    op.alter_column('schedules', 'schedule_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('THEORY', 'PRACTICAL'),
               existing_comment='排期类型',
               existing_nullable=False)
    # ### end Alembic commands ###
