"""change_candidate_status_to_string

Revision ID: f2fad9704da5
Revises: 6a7dd1e21d28
Create Date: 2025-08-01 14:34:35.142167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2fad9704da5'
down_revision: Union[str, Sequence[str], None] = '6a7dd1e21d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'status',
               existing_type=mysql.ENUM('待审核', '已审核', '已拒绝', '活跃', '非活跃'),
               type_=sa.String(length=20),
               nullable=True,
               comment='考生状态',
               existing_server_default=sa.text("'待审核'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('待审核', '已审核', '已拒绝', '活跃', '非活跃'),
               nullable=False,
               comment=None,
               existing_comment='考生状态',
               existing_server_default=sa.text("'待审核'"))
    # ### end Alembic commands ###
